// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "http://neoprime.it",
    id: "b13df1ec-9522-4282-8de1-fd03b169bc1e",
    method: "GET",
    address: "http://neoprime.it/"
  });
}
